version: "3.4"

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    command: --default-authentication-plugin=mysql_native_password
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-symfony}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-secret}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data:rw
    ports:
      - '3306:3306'

  php:
    depends_on:
      - database
    build:
      context: ./docker/php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:secret@database:3306/symfony?serverVersion=8&charset=utf8mb4"

  nginx:
    depends_on:
      - php
      - database
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html:ro,cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf